# https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.callbacks.ModelCheckpoint.html


# To avoiding copying of loss and metric names, during hydra initialization
# there is custom resolver which replaces __loss__ to loss.__class__.__name__
# and __metric__ to main_metric.__class__.__name__,
# for example: ${replace:"__metric__/valid"}
# Use quotes for defining internal value in ${replace:"..."} to avoid
# grammar problems with hydra config parser.


_target_: lightning.pytorch.callbacks.ModelCheckpoint
every_n_epochs: 100
save_top_k: -1
save_last: True
verbose: False
dirpath: ${paths.output_dir}/checkpoints
filename: "epoch{epoch:03d}"
auto_insert_metric_name: False