
# finetune.yaml
_target_: models.linear_classifier.FineTuneClassifier

base_model: 
  _target_: models.sup_cont.ContrastiveResNet50.load_from_checkpoint
  _args_:
    - ${base_model_path}
num_ftrs: 2048
num_classes: 2
max_epochs: ${trainer.max_epochs}
lr: 0.001
nesterov: False
p_dropout: 0.0
weight_decay: 0
hidden_dim_size: null
warmup_epochs: 0
optimizer_name: "adam"